- name: split module
  hosts: all
  vars:
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
    tomcat_url_split: "{{tomcat_url.split('/') | last}}"
    tomcat_dir: "{{tomcat_url_split | regex_replace ('.tar.gz',)}}"

  tasks: 
    - name: split_url
      debug: 
        msg: "{{tomcat_dir}}"