- name: download java
  package:
    name: "{{item}}"
    state: present
  loop: 
    # - epel-release
    - java

- name: download tomcat
  unarchive:
    src: "{{tomcat_url}}"
    dest: "{{tomcat_dir1}}"
    remote_src: True

- name: copy war file
  get_url:
    url:  https://studentwar-new.s3.ap-south-1.amazonaws.com/studentapp-2.2-SNAPSHOT.war
    dest: "{{tomcat_dir}}/webapps"


    
- name: Start tomcat
  command: "{{tomcat_dir}}/bin/catalina.sh start"  
  
- name: copy jar file 
  get_url:
    url: https://studentwar-new.s3.ap-south-1.amazonaws.com/mysql-connector.jar
    dest: "{{tomcat_dir}}/lib/"

- name: copy context.xml
  template: 
    src: context.xml
    dest: "{{tomcat_dir}}/conf/context.xml"
